# command: docker compose up --build
# https://medium.com/@jewelski/quickly-set-up-a-local-postgres-database-using-docker-5098052a4726
# https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/#Why-should-you-containerize-Postgres
# https://github.com/docker/awesome-compose/tree/master/postgresql-pgadmin
# docker compose -f .docker/compose.yaml up
# docker compose -f .docker/compose.yaml down
name: nest-sandbox-container
services:
  # Application
  # nest-sandbox-app:
  #   build:
  #     context: ../
  #     dockerfile: docker/dockerfile
  #   container_name: nest-sandbox-app
  #   env_file:
  #     - ../.env.dev
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped

  # Database
  nest-sandbox-postgres:
    container_name: nest-back-sandbox
    image: postgres:15.5-alpine3.18
    restart: unless-stopped
    env_file: ../.env.dev
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    hostname: localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Redisstack to try
  # https://www.emmanuelgautier.com/blog/snippets/redis-stack-docker-compose
  
  # Redis
  nest-sandbox-redis:
    image: redis:latest
    container_name: nest-sandbox-redis
    restart: always
    hostname: localhost
    ports:
      - "6379:6379"
    volumes:
      - redis_volume_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

  # RedisInsight
  nest-sandbox-redis-insight:
    image: redislabs/redisinsight:latest
    container_name: nest-sandbox-redis-insight
    restart: always
    hostname: localhost
    ports:
      - "5540:5540"
    volumes:
      - redis-insight_volume_data:/db

volumes:
  postgres-data:
  redis_volume_data:
  redis-insight_volume_data:
networks:
  nest-sandbox-network:
    external: true
